// <auto-generated />
namespace EfOracleCodeFirstConsole.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class YeniKolonTest5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YeniKolonTest5));
        
        string IMigrationMetadata.Id
        {
            get { return "201805121600326_YeniKolonTest5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
